### ISSUE TITLE
Connect with ocean-icons project (Android)

### ISSUE THREAD

**Issue by eltongarbin** [ocean-ds/ocean-android#119]
**Is your feature request related to a problem? Please describe.**
The blu iconography must be unique for all platforms, for that reason there's a project [ocean-icons](https://github.com/ocean-ds/ocean-icons) that centralizes the SVGs.

**Describe the solution you'd like**
Like we did for `ocean-tokens` we can integrate this project with the `ocean-icons` and export an android version of these icons.

**Comment by mariofelesdossantosjunior** [comment]
Já fiz essa implementação, atualmente estamos usando os icones atraves de tokens do ocean icons
