### ISSUE TITLE
Adjust Checkbox and text size (Android)

### ISSUE THREAD

**Issue by julianasouza-s** [ocean-ds/ocean-android#215]
**Checkbox**
- width: 20px
- height: 20px
- icon: 16px x 16px

**Text**
- font size: 14px

Should be something like this:
![image](https://user-images.githubusercontent.com/79791418/159753906-19b08862-0cbb-42ce-af3a-6890d4639436.png)

**Comment by mariofelesdossantosjunior** [comment]
Implementado
